#!/bin/sh
set -eu
input=""
expression=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    -i) input="$2"; shift 2 ;;
    -e) expression="$2"; shift 2 ;;
    *) shift ;;
  esac
done
field="${expression##*.}"
node -e 'const j=JSON.parse(require("fs").readFileSync(process.argv[1],"utf8")); const v=j.results?.[0]?.[process.argv[2]]; if (v !== undefined && v !== null) process.stdout.write(String(v))' "$input" "$field"
